name: Lint

on: [push]

jobs:
  clang-format:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v1

    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.3.1
      with:
        # List of extensions to check
        extensions: cpp,h

  max-path:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Max Path
      uses: graebm/max-path-action@v1
      with:
        limit: 150
